import { useNavigate } from "react-router";
import { SidebarTrigger } from "~/components/ui/sidebar";
import { Header } from "../../../components/Header";
import { Button } from "~/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { ArrowLeft, ChevronDown, TrendingUp } from "lucide-react";
import StatsCard from "../../../components/StatsCard";
import { TrendList } from "../../../components/TrendList";
import { BranchStatsTable } from "../../../components/BranchStatsTable";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';

export default function ViewProfitReport() {
  const navigate = useNavigate();

  // Mock Data
  const profitData = {
      amount: "12,450 RWF",
      trend: "12% vs last month"
  };

  const branchRevenues = [
      { name: "CAVM", amount: 1000, max: 1200 },
      { name: "NYAGATRE", amount: 950, max: 1200 },
      { name: "BUSOGO", amount: 800, max: 1200 },
      { name: "RUKARA", amount: 1100, max: 1200 },
      { name: "HUYE", amount: 1050, max: 1200 },
  ];

  const dateRevenues = [
      { date: "2026-02-08", amount: 1000, max: 1200 },
      { date: "2026-02-09", amount: 100, max: 1200 },
      { date: "2026-02-10", amount: 100, max: 1200 },
  ];

  const profitByBranch = [
      { branch: "CAVM", regular: 20, vip: 20, vvip: 20 },
      { branch: "Downtown", regular: 12, vip: 12, vvip: 12 },
      { branch: "Kimironko", regular: 68, vip: 68, vvip: 68 },
  ];

  const monthlyRevenueData = [
      { name: 'Jan', value: 1600 },
      { name: 'Feb', value: 1200 },
      { name: 'Mar', value: 3000 },
      { name: 'Apr', value: 1400 },
      { name: 'May', value: 2000 },
      { name: 'Jun', value: 1800 },
  ];

  return (
    <main className="dashboard wrapper flex flex-col gap-6 p-4 md:p-6 bg-slate-50 min-h-screen">
      
       <div className="flex flex-col items-center gap-4">
          <Header
            title="View Profit Report"
            description="Track activity, trends, and popular destinations in real time"
            action={
              <SidebarTrigger className="rounded-md p-1 border border-transparent md:border-slate-200" />
            }
          />
           <div className="w-full p-0 flex justify-between items-center">
                <Button variant="ghost" size="icon" className="flex justify-start pl-0 hover:bg-transparent hover:text-blue-600 w-auto" onClick={() => navigate(-1)}>
                    <ArrowLeft className="h-5 w-5 mr-2" /> Back
                </Button>
                
                <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                        <Button variant="outline" className="min-w-[120px] justify-between bg-white">
                            Week <ChevronDown className="h-4 w-4 opacity-50 ml-2" />
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                        <DropdownMenuItem>Week</DropdownMenuItem>
                        <DropdownMenuItem>Month</DropdownMenuItem>
                        <DropdownMenuItem>Year</DropdownMenuItem>
                    </DropdownMenuContent>
                </DropdownMenu>
            </div>
      </div>

        {/* Top Section: Profit & Branch Revenue */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Profit Card */}
            <StatsCard
                title="Profit"
                value="12,450 RWF"
                currentDay={12450}
                lastDayCount={11116}
                trendLabel="vs last month"
            />

            {/* Branch's Revenue */}
            <div className="h-full">
                 <TrendList
                    title="Branch's Revenue"
                    items={branchRevenues.map(b => ({
                        label: b.name,
                        value: b.amount,
                        formattedValue: `${b.amount} RWF`,
                        key: b.name
                    }))}
                    limit={2}
                 />
            </div>
        </div>

        {/* Middle Section: Revenue History & Profit Table */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
             {/* Revenue History */}
             <div className="h-full">
                 <TrendList
                    title="Revenue (This week | Month | Year | Weeks)"
                    items={dateRevenues.map(d => ({
                        label: d.date,
                        value: d.amount,
                        formattedValue: `${d.amount} RWF`,
                        key: d.date
                    }))}
                    limit={2}
                 />
             </div>

             {/* Profit Generated by Branch Table */}
             <BranchStatsTable
                title="Profit Generated by Branch"
                data={profitByBranch.map(p => ({
                    branch: p.branch,
                    Regular: p.regular,
                    VIP: p.vip,
                    VVIP: p.vvip,
                }))}
                columns={[
                    { header: "Branch", accessorKey: "branch", align: "left" },
                    { header: "Regular", accessorKey: "Regular", align: "left" },
                    { header: "VIP", accessorKey: "VIP", align: "left" },
                    { header: "VVIP", accessorKey: "VVIP", align: "left" },
                ]}
                showTotalRow={false}
             />
        </div>

        {/* Bottom Section: Monthly Revenue Chart */}
        <Card className="border-slate-100 shadow-sm max-w-2xl">
            <CardHeader>
                <CardTitle className="text-base font-bold text-gray-900">Monthly Revenue</CardTitle>
            </CardHeader>
            <CardContent>
                <div className="h-[300px] w-full mt-4">
                    <ResponsiveContainer width="100%" height="100%">
                        <AreaChart
                            data={monthlyRevenueData}
                            margin={{ top: 10, right: 30, left: 0, bottom: 0 }}
                        >
                            <defs>
                                <linearGradient id="colorValue" x1="0" y1="0" x2="0" y2="1">
                                    <stop offset="5%" stopColor="#3B82F6" stopOpacity={0.8}/>
                                    <stop offset="95%" stopColor="#3B82F6" stopOpacity={0}/>
                                </linearGradient>
                            </defs>
                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0" />
                            <XAxis 
                                dataKey="name" 
                                axisLine={false} 
                                tickLine={false} 
                                tick={{ fill: '#64748B', fontSize: 12 }} 
                                dy={10}
                            />
                            <YAxis 
                                axisLine={false} 
                                tickLine={false} 
                                tick={{ fill: '#64748B', fontSize: 12 }} 
                                tickFormatter={(value) => `${value / 1000}k`}
                            />
                            <Tooltip 
                                contentStyle={{ backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                                itemStyle={{ color: '#1E293B' }}
                                formatter={(value: number) => [`${value} RWF`, 'Revenue']}
                            />
                            <Area 
                                type="monotone" 
                                dataKey="value" 
                                stroke="#3B82F6" 
                                strokeWidth={2}
                                fillOpacity={1} 
                                fill="url(#colorValue)" 
                                activeDot={{ r: 6, strokeWidth: 2, stroke: '#fff' }}
                            />
                        </AreaChart>
                    </ResponsiveContainer>
                </div>
            </CardContent>
        </Card>

    </main>
  );
}
